### PR TITLE
Fix branchLookup for Mumbai

### LINKED ISSUE #138: Do you have a branch in Mumbai?  -> Sorry currently we don't have branch details for undefined
2 problems...

1) "undefined" is just a coding error on that error message.  In this case it has a location to use.

2) Why not return details for Mombai?  This is happening because this pattern was split into US/India versions.  The India version has both Mombai and NY while the US version is just unable to return details when specifically asked about Mombai.  Why not answer?

### PR DESCRIPTION
**Pull request by markstur**
Fixes #138

* The error message had undefined instead of the location
* Allow the US version to have both branches like the India version does.

### CODE REVIEW

File: app.js [hunk 1]
```diff
@@ -485,7 +485,9 @@ function checkForLookupRequests(output, callback) {
     } else if (data.context.action.lookup === 'branch') {
       console.log('************** Branch details *************** InputText : ' + payload.input.text);
       const loc = data.context.Location.toLowerCase();
-      bankingServices.getBranchInfo(loc, function(err, branchMaster) {
+      // Use the master (India) lookup for getBranchInfo
+      // It can return either India or US.
+      bankingServicesIN.getBranchInfo(loc, function(err, branchMaster) {
```
Comment (sanjeevghimire) [inline app.js]: `const bankingServicesIN = require('./banking_services');`
should this be renamed `banking_services_in`?

Comment (sanjeevghimire) [reply app.js]: Others LGTM

Comment (markstur) [reply app.js]: I'll say no because we've been renaming/fixing things and it just breaks stuff.  Should the app be rewritten to be a better example?  Yes, but not until we have a test plan, script, etc... to make sure we don't add regressions.

Comment (sanjeevghimire) [reply app.js]: the variable name doesn't align with the file name. Since this is change for filename and it might break things, merging it for now. But we can revisit that later.
